name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Build image
    runs-on: [self-hosted]

    steps:
    - name: Docker
      run: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            chmod +x get-docker.sh
            sh get-docker.sh

    - name: Check out code
      uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
          registry: jfrog.it-academy.by
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.23.3'
      id: install

    - name: Build, tag, and push image to JFrog
      env:
        JFROG_REGISTRY: jfrog.it-academy.by
        JFROG_REPOSITORY: public/denisareshkevich-project
        IMAGE_TAG: ${{ github.sha }}
      run: |
        ls -la
        docker build -t $JFROG_REGISTRY/$JFROG_REPOSITORY:$IMAGE_TAG -t $JFROG_REGISTRY/$JFROG_REPOSITORY:latest .
        docker push -a $JFROG_REGISTRY/$JFROG_REPOSITORY

    - name: Deploy to K8S
      run: |
        kubectl apply -f k8s/deployment.yaml

